---
include:
  - board: ergohaven
    shield: k03_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: k03_left
    keymap: k03_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: k03_left_ruen-ergohaven-zmk
  - board: ergohaven
    shield: k03_right
  
